# Generated by Django 3.0.6 on 2020-10-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0017_auto_20201008_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='vehicle_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
